name       : xmonad-contrib
version    : 0.17.1
release    : 4
source     :
    - https://hackage.haskell.org/package/xmonad-contrib-0.17.1/xmonad-contrib-0.17.1.tar.gz : ab378337f48f8f359f6ff6425b1d7cfefccf336e527c3a7606d070e567479253
license    : BSD-3-Clause
component  : programming.haskell
summary    : Third party extensions for xmonad
description: |
    Third party tiling algorithms, configurations and scripts to xmonad, a tiling window manager for X.
builddeps  :
    - haskell-cabal-install
    - haskell-random-devel
    - haskell-x11-xft-devel
    - xmonad-devel
rundeps    :
    - devel :
        - haskell-random-devel
        - haskell-x11-xft-devel
        - xmonad-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
