name       : xmonad-contrib
version    : '0.16'
release    : 3
source     :
    - https://hackage.haskell.org/package/xmonad-contrib-0.16/xmonad-contrib-0.16.tar.gz : ad72c38de1bf4f9e176bd0da7ee62a6153b03c9087313b3d4782f365f77caddd
license    : BSD-3-Clause
component  : programming.haskell
summary    : Third party extensions for xmonad
description: |
    Third party tiling algorithms, configurations and scripts to xmonad, a tiling window manager for X.
builddeps  :
    - haskell-cabal-install
    - haskell-old-time-devel
    - haskell-random-devel
    - haskell-semigroups-devel
    - haskell-x11-xft-devel
    - xmonad-devel
rundeps    :
    - devel:
        - haskell-x11-xft-devel
        - haskell-old-time-devel
        - haskell-random-devel
        - haskell-semigroups-devel
        - xmonad-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
