name       : xmonad-contrib
version    : 0.13
release    : 1
source     :
    - https://hackage.haskell.org/package/xmonad-contrib-0.13/xmonad-contrib-0.13.tar.gz : a760827fe5b1f99d783f52ccbb72b272d02d53daa26757363cde3ceba014476e
license    : BSD-3-Clause
component  : programming.haskell
summary    : Third party tiling algorithms, configurations and scripts to xmonad, a tiling window manager for X.
description: |
    Third party tiling algorithms, configurations and scripts to xmonad, a tiling window manager for X.
builddeps  :
    - pkgconfig(xft)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - haskell-cabal-install
    - haskell-old-time
    - haskell-x11-xft
    - xmonad
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
